### ISSUE TITLE
Диалог в плюрализе

### ISSUE THREAD

**Issue by dead23angel** [wapmorgan/Morphos#11]
Если 1 то все верно диалог
Если 2,3,4 то вместо диалога, пишет диалогЯ

**Comment by wapmorgan** [comment]
Какую версию используете? Сейчас последняя 3.2.2, в ней все правильно склоняется:
- `http://morphos.tech/try/numerals?number=&word=%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3`
- `var_dump(morphos\Russian\pluralize(2, 'диалог'));` => `string(16) "2 диалога"`

**Comment by dead23angel** [comment]
Я использую пакет wapmorgan/morphos-blade, была версия 1.4.0, с ним ставилась версия  wapmorgan/morphos 2.3.5, сейчас выполнил composer update поставилось wapmorgan/morphos-blade 1.5.0 и wapmorgan/morphos 3.0.9 и там этого бага уже нет, извиняюсь за то что потревожил.
