### ISSUE TITLE
Неправильная логика для предлогов в/во

### ISSUE THREAD

**Issue by evg555** [wapmorgan/Morphos#118]
https://github.com/wapmorgan/Morphos/blob/ec18034d4a439139902c769a64bb67e59e3402a8/src/Russian/RussianLanguage.php#L288

Необходимо дополнить правило, что вторая буква после  'в' или 'ф' должна быть гласная - тогда будет предлог  'в', а если согласная - 'во'.
Пример:
в Феодосии, в Воркуте, в ванне, в весенней луже
во Владивостоке, во флаконе, во временном хранилище, во фракции

**Comment by wapmorgan** [comment]
**3.2.26** release
