### ISSUE TITLE
Винительный падеж, множественное число не всегда верно

### ISSUE THREAD

**Issue by Philosoft** [wapmorgan/Morphos#12]
Пока наткнулся только на 1 проблему - слово "халат"

```php
echo morphos\Russian\NounPluralization::getCase("халат", "винительный") . PHP_EOL;
 // халата
``` 

а должно быть "халаты"

**Comment by gromdron** [comment]
Очень странно, ведь согласно http://sklonenie-slova.ru/halat и http://dicti.info/page/halat.php должно быть "халат" для единственного числа и "халаты" для множественного. 

А согласно https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%B4%D0%B5%D0%B6

Нужно задать вопрос: "Винить кого/что?" и получается "Винить халат" (ед.ч.) или "Винить халаты" (мн.ч).
Вы думаете правильнее будет "халаты" ?

**Comment by Philosoft** [comment]
Винить - халат/халаты. Нет - халата/халатов. Много/мало/несколько - халатов. Один - халат. Мой конкретный пример "мы продаём халаты". Так что я за "халаты". btw, единственное место, в которое я смотрел, кроме своей головы, [викисловарь](https://ru.wiktionary.org/wiki/%D1%85%D0%B0%D0%BB%D0%B0%D1%82)

На всякий случай, чтобы избежать недопонимания. Строчкой `morphos\Russian\NounPluralization::getCase("халат", "винительный")` я хочу получить слово "халат" в винительном падеже, множественном числе, а получаю (по моему разумению) в родительном падеже и единственном числе.

Почему я написал предыдущий абзац - я не вижу, что в вашем комментарии противоречит моему - все приведённые вами источники и выводы совпадают с моим утверждением "слово 'халат' в винительном падеже, множественном числе должно иметь форму 'халаты'"

**Comment by gromdron** [comment]
Оу... и куда я смотрел - NounPluralization же :(
Полностью согласен - халаты.

**Comment by wapmorgan** [comment]
Исправлено в dev-master, как только чутка наберется изменений - будет очередной релиз. Спасибо за информацию!

**Comment by Philosoft** [comment]
фигасе скорость) спасибо за столь быструю реакицю)

для истории: исправлено в abd6d28b8a4df99f63bdc27650a2e4356674a0ad

**Comment by wapmorgan** [comment]
Да не за что :) Если что, проверять можно теперь и на сайте: http://morphos.tech/try/numerals?number=&word=%D1%85%D0%B0%D0%BB%D0%B0%D1%82
