### ISSUE TITLE
Множественное число существительных, оканчивающихся на С и Ж

### ISSUE THREAD

**Issue by alenaobraz** [wapmorgan/Morphos#120]
Добрый день.

Сейчас множественное число в именительном падеже для существительных, оканчивающихся на С, добавляет А :
`\morphos\Russian\NounPluralization::getCase('матрас', 'именительный')`
_матраса_

`\morphos\Russian\NounPluralization::getCase('кактус', 'именительный')`
_кактуса_

А должно быть Ы:
[            $forms[Cases::IMENIT] = $prefix.'ы';](https://github.com/wapmorgan/Morphos/blob/ec18034d4a439139902c769a64bb67e59e3402a8/src/Russian/NounPluralization.php#L199)

Множественное число в именительном падеже для существительных, оканчивающихся на Ж, тоже добавляет А:

`\morphos\Russian\NounPluralization::getCase('коттедж', 'именительный')`
_коттеджа_
А должно быть И:
```
elseif (in_array($last, ['ж'], true)) {
            $forms[Cases::IMENIT] = $prefix.'и';
        }
```

Благодарю за ваш суперполезный плагин!

**Comment by wapmorgan** [comment]
**3.2.24** release
