### ISSUE TITLE
Некорректное склонение фамилий с окончанием на "Й"

### ISSUE THREAD

**Issue by mikhailaleksandrov** [wapmorgan/Morphos#121]
Мужские фамилии, оканчивающиеся на «й», склоняются некорректно:

Как сейчас:
И.п. Брынзей, Бакай, Грицай
Р.п. Брынзейа, Бакайа, Грицайа
Т.п. Брынзейом, Бакайом, Грицайом

Как должно быть:
Женские фамилии не склоняются
Мужские фамилии:

И.п. Брензей, Бакай, Грицай, Левай
Р.п. Брынзея, Бакая, Грицая, Левая
Д.п. Брынзею, Бакаю, Грицая, Леваю
В.п. Брынзея, Бакая, Грицая, Левая
Т.п. Брынзеем, Бакаем, Грицаем, Леваем
П.п. Брынзее, Бакае, Грицае, Левае

**Comment by wapmorgan** [comment]
**3.2.26** release
