### ISSUE TITLE
Некорректное склонение фамилий с окончанием на "Й" (новые кейсы)

### ISSUE THREAD

**Issue by Jekis** [wapmorgan/Morphos#122]
Мужские фамилии, оканчивающиеся на «й» - формируются некорректно:

**Как сейчас:**

И.п. Лукелий, Галянтий, Стуккей
Р.п. Лукелого, Галянтого, Стуккейа
Т.п. Лукелым, Галянтым, Стуккейом

**Как должно быть:**

Женские фамилии не склоняются
Мужские фамилии:

И.п.	Лукелий	Галянтий	Стуккей
Р.п.	Лукелия	Галянтия	Стуккея
Д.п.	Лукелию	Галянтию	Стуккею
В.п.	Ликелия	Галянтия	Стуккея
Т.п.	Лукелием	Галянтием	Стуккеем
П.п.	Ликелии	Галянтии	Стуккее

Неправильное склонение фамилии Цой.

**Как сейчас:** 

И.п. Цой
Р.п. Цого
Т.п. Цым
 
**Как должно быть:**

Фамилия Цой у женщин не склоняется
Мужские фамилии:

И.п.	Цой
Р.п.	Цоя
Д.п.	Цою
В.п.	Цоя
Т.п.	Цоем
П.п.	Цое

**Comment by Jekis** [comment]
@wapmorgan, здравствуйте! Есть надежда на исправление этого бага?

**Comment by wapmorgan** [comment]
In 3.2.28

**Comment by ymakarov** [comment]
Кажется, что теперь проблема со склонением фамили Лановой. В родительном падеже получается Лановоя.
