### ISSUE TITLE
Неверное склонение слова "русский"

### ISSUE THREAD

**Issue by ivankuraev** [wapmorgan/Morphos#137]
Неверно склоняется слово "русский".

`morphos\Russian\NounDeclension::getCase( 'русский', 'родительный' ) => 'русскего'`

**Comment by wapmorgan** [comment]
Пользуйтесь правильным классом.
`morphos\Russian\AdjectiveDeclension::getCases("русский")`

Это прилагательное, которое может использоваться как подлежащее или дополнение.
