### ISSUE TITLE
Склонение сложных ФИО

### ISSUE THREAD

**Issue by jeshio** [wapmorgan/Morphos#14]
пример с неверным склонением

Сатыбалды-Уулу Салмонбек Сардарбекович

выход - Ь вместо Е:
Родительный кого? чего? | Сатыбалды-Уулу Салмонбька Сардарбековича
-- | --
Дательный кому? чему? | Сатыбалды-Уулу Салмонбьку Сардарбековичу
Винительный кого? что? | Сатыбалды-Уулу Салмонбька Сардарбековича
Творительный кем? чем? | Сатыбалды-Уулу Салмонбьком Сардарбековичем
Предложный о ком? о чем? | о Сатыбалды-Уулу Салмонбьке Сардарбековиче

**Comment by wapmorgan** [comment]
Ок, исправлено в dev-master.
