### ISSUE TITLE
Fix russian ordinal numbers

### ISSUE THREAD

**Issue by WAXII** [wapmorgan/Morphos#140]
src/Russian/OrdinalNumeralGenerator.php

    /**
     * @var string[]
     * @phpstan-var array<int, string>
     */
    protected static $words = [
        1   => 'первый',
        2   => 'второй',
        3   => 'третий',
        4   => 'четвертый',
        5   => 'пятый',
        6   => 'шестой',
        7   => 'седьмой',
        8   => 'восьмой',
        9   => 'девятый',
        10  => 'десятый',
        11  => 'одиннадцатый',
        12  => 'двенадцатый',
        13  => 'тринадцатый',
        14  => 'четырнадцатый',
        15  => 'пятнадцатый',
        16  => 'шестнадцатый',
        17  => 'семнадцатый',
        18  => 'восемнадцатый',
        19  => 'девятнадцатый',
        20  => 'двадцатый',
        30  => 'тридцатый',
        40  => 'сороковой',
        50  => 'пятидесятый',
        60  => 'шестидесятый',
        70  => 'семидесятый',
        80  => 'восьмидесятый',
        90  => 'девяностый',
        100 => 'сотый',
        200 => 'двухсотый',
        300 => 'трехсотый',
        400 => 'четырехсотый',
        500 => 'пятисотый',
        600 => 'шестисотый',
        700 => 'семисотый',
        800 => 'восьмисотый',
        900 => 'девятисотый',
    ];

Errors fixed in 50, 60, 70, 80, 800

**Comment by wapmorgan** [comment]
3.2.29
