### ISSUE TITLE
Неверное склонение в родительный падеж населённых пунктов, похожих на существительные в множественном числе

### ISSUE THREAD

**Issue by yJIyJIy** [wapmorgan/Morphos#147]
Такие населённые пункты как Горки, Гусёнки: 
деревня Горки - вместе с администратиным названием - склоняется нормально - остаётся Горки, а вот отдельно:
родительный падёж: ожидается "у Горок" - получается "у Горков"

Гусёнки - вместо Гусёнок - у Гусёнков
Химки - вместо Химок - у Химков

Но при этом правильно:
Барсуки - у Барсуков
Родники - у Родников

Как мне кажется, нужно либо в исключения добавлять
Либо определять является ли название множественным числом, пытаться получить из него единственное и превращать в множественное в родительном падеже:
Гусёнки - Гусёнка - Гусёнков
Химки - Химка - Химок

**Comment by bzaar** [comment]
Так как правильно, Гусёнков или Гусёнок?

**Comment by bzaar** [comment]
Ваше предложение можно по-разному прочитать: 

> Гусёнки - вместо Гусёнок - у Гусёнков

Вместо правильного или вместо того, что сейчас программа выдает?

**Comment by yJIyJIy** [comment]
> Ваше предложение можно по-разному прочитать:
> 
> > Гусёнки - вместо Гусёнок - у Гусёнков
> 
> Вместо правильного или вместо того, что сейчас программа выдает?

правильно - Гусёнок
не правильно - Гусёнков

**Comment by yJIyJIy** [comment]
> Спасибо! А можно еще поинтересоваться, откуда вы знаете, как правильно?

правила подтверждающего/опровергающего не нашёл - основываюсь на аналогичности с Химками

**Comment by bzaar** [comment]
> основываюсь на аналогичности с Химками

А почему не по аналогии с Гуськи или Петушки, например?

**Comment by yJIyJIy** [comment]
> > основываюсь на аналогичности с Химками
> 
> А почему не по аналогии с Гуськи или Петушки, например?

Согласен - нет очевидного правила - взял слова, заканчивающиеся на "рки" от сюда https://makeword.ru/end/%D1%80%D0%BA%D0%B8

Понятного правила склонения не подобрал

арки - арок
бирки - бирок
горки - горок
дырки - дырок
кирки - кирок
лерки - лерок
марки - марок
etc..

но:
курки - курков
нырки - нырков
сырки - сырков
окурки - окурков
etc..

В целом со всем "ки" такая проблема

Вероятно не будет исправлено, возможно стоит указать в документации, чтобы с осторожностью относились к существительным в множественном числе с окончанием "ки"
