### ISSUE TITLE
Idiotic api change

### ISSUE THREAD

**Issue by alpha-and-omega** [wapmorgan/Morphos#16]
Change order of arguments of pluralize() 
Suck you!

**Comment by alpha-and-omega** [comment]
At least make it order-agnostic, this broke my production system.

**Comment by wapmorgan** [comment]
Sorry for inconvenience that this change was made without increasing minor version part of Morphos. 
You can downgrade to **3.2.2** version, in which this update [was made](https://github.com/wapmorgan/Morphos/releases/tag/3.2.2).

**Comment by alpha-and-omega** [comment]
You also changed output format, uhgggg! 3.0.9 actually.

**Comment by wapmorgan** [comment]
I've updated `pluralize()` and `NounPluralization::pluralize()` in 3.2.7: now you can swap arguments and result will be the same: `pluralize('дом', 2)` and `pluralize(2, 'дом')` are identical
