### ISSUE TITLE
Склонение городов

### ISSUE THREAD

**Issue by VitalyArt** [wapmorgan/Morphos#17]
Сталкнулся с тем, что неверно скланяет город "Ростов-на-Дону".
Ещё на сайте http://morphos.tech/try/names при клике на вкладки ничего не происходи.

**Comment by wapmorgan** [comment]
Спасибо, исправлено. Сайт работает, попробуйте из другого браузера.

**Comment by VitalyArt** [comment]
https://github.com/wapmorgan/Morphos/pull/21
Я тут немного по другому сделал, только вот у меня тест не проходит.
```
 Array (
     'nominative' => 'Ростов-на-Дону'
     'genitive' => 'Ростова-на-Дону'
     'dative' => 'Ростову-на-Дону'
     'accusative' => 'Ростов-на-Дону'
-    'ablative' => 'Ростовом-на-Дону'
+    'ablative' => 'Ростовым-на-Дону'
     'prepositional' => 'Ростове-на-Дону'
 )
```

Это из-за того, что "Ростов" в творительный падеже скланяется как "Ростовым", а должен "Ростовом".
http://morphos.tech/try/geography?input=%D0%A0%D0%BE%D1%81%D1%82%D0%BE%D0%B2
