### ISSUE TITLE
Ошибка склонения - ванная

### ISSUE THREAD

**Issue by etodesign** [wapmorgan/Morphos#19]
1 ванная  - OK
2 ванной - ?
3 ванной - ?
4 ванной -?
5 ванных - OK 
6 ванных  - OK
7 ванных - OK
8 ванных  - OK
9 ванных  - OK
10 ванных  - OK
11 ванных  - OK
11 ванных  - OK

**Comment by wapmorgan** [comment]
Благодарю, исправлено.
