### ISSUE TITLE
Неверное склонение городов

### ISSUE THREAD

**Issue by ilyaplot** [wapmorgan/Morphos#20]
https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B3%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5#Славянские_названия,_оканчивающиеся_на_-ов(о),_-ёв(о),_-ев(о),_-ин(о),_ын(о)

Города, оканчивающиеся на ово, ёво, ево, ино, ыно не должны склоняться.

**Comment by wapmorgan** [comment]
> Однако, если топоним употребляется без родового географического термина, его склонение по падежам обязательно. Таким образом, будем говорить: улицы района Жулебино, но улицы Жулебина; живу в районе Жулебино, но живу в Жулебине[5].
> Если же родового слова нет, то нормативны оба варианта, склоняемый (старый) и несклоняемый (новый). При этом склоняемый вариант соответствует строгой литературной норме (и рекомендуется, например, для речи дикторов).
> 	Географические названия на -ово, -ево (-ёво) и -ино, -ыно: Иваново, Бирюлёво, Кунцево, Сараево, Болдино, Бородино, Голицыно и подобные в современной разговорной, профессиональной, газетной речи обнаруживают тенденцию к неизменяемости. Несмотря на это, в письменной речи, в соответствии с действующими грамматическими правилами, географические названия на -ов(о), -ёв(о), -ев(о), -ин(о), -ын(о) склоняются: В небе над Тушином, Речь идёт об аэропорте в Шереметьево.
Оттуда я правила и брал.
