### ISSUE TITLE
неправильно сколняет Правила дорожного движения

### ISSUE THREAD

**Issue by 111ypuk** [wapmorgan/Morphos#24]
Именительный кто? что? | Правила Дорожного Движения
Родительный кого? чего? | Правилы Дорожного Движении
Дательный кому? чему? | Правиле Дорожного Движении
Винительный кого? что? | Правилу Дорожного Движению
Творительный кем? чем? | Правилой Дорожного Движенией
Предложный о ком? о чем? | Правиле Дорожного Движении

**Comment by wapmorgan** [comment]
Библиотека и не предназначена для склонения таких сочетаний слов.
