### ISSUE TITLE
Неправильно склоняются географические названия оканчивающиеся на "ий"

### ISSUE THREAD

**Issue by dimka** [wapmorgan/Morphos#26]
Напрвильно: http://morphos.tech/try/geography?input=%D0%9C%D0%B0%D0%B2%D1%80%D0%B8%D0%BA%D0%B8%D0%B9
Правильно: http://residentname.ru/mu/

**Comment by wapmorgan** [comment]
Это немного не то, что должно склоняться. Это название жителей местности (https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%B9).

**Comment by wapmorgan** [comment]
Это название республики, причем использующее нестандартные правила склонения (а именно, склонение по правилам личного имени).
Пока что нет необходимости склонять такое название, поэтому функциональность для исправления не будет вводиться.
Но Вы можете использовать `FirstNamesInflection::getCases()`:
```php
var_dump(morphos\Russian\FirstNamesInflection::getCases('Маврикий', morphos\Gender::MALE));
=>
array(6) {
  ["nominative"]=>
  string(16) "Маврикий"
  ["genitive"]=>
  string(16) "Маврикия"
  ["dative"]=>
  string(16) "Маврикию"
  ["accusative"]=>
  string(16) "Маврикия"
  ["ablative"]=>
  string(18) "Маврикием"
  ["prepositional"]=>
  string(16) "Маврикии"
}

```
