### ISSUE TITLE
pluralize для слова "комментарий" некорректное

### ISSUE THREAD

**Issue by amorphine** [wapmorgan/Morphos#32]
В первую очередь спасибо за классную библиотеку)

Небольшая трабла:
[Ссылка на http://morphos.io](http://morphos.io/try/numerals?number=0&word=%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9)

В частности у меня: 

> 0 комментарых

Используемая версия 3.2.11

**Comment by wapmorgan** [comment]
Спасибо за фидбек. Исправлю в ближайшее время.

**Comment by wapmorgan** [comment]
Исправлено: http://morphos.io/try/numerals?number=&word=%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9
