### ISSUE TITLE
Неправильно склоняется Торжок, Вышний Волочек

### ISSUE THREAD

**Issue by apoldev** [wapmorgan/Morphos#34]
Добрый День.
Нашел проблему. Неверно склоняет некоторые города Торжок и Вышний Волочек

http://morphos.io/try/geography?input=%D0%A2%D0%BE%D1%80%D0%B6%D0%BE%D0%BA

В предложном: Торжоке и Вышнем Волочеке, а надо Торжке, Вышнем Волочке

**Comment by apoldev** [comment]
Также Камень-на-Оби неверно склоняется
http://morphos.io/try/geography?input=%D0%9A%D0%B0%D0%BC%D0%B5%D0%BD%D1%8C-%D0%BD%D0%B0-%D0%9E%D0%B1%D0%B8

**Comment by wapmorgan** [comment]
Спасибо за фидбек. У меня нет сейчас столько свободного времени и желания, чтобы это поправить. Если вы обладаете достаточными знаниями, можете сделать pull request. Если нет, то я как-нибудь в будущем займусь этой проблемой.

**Comment by Nappsel** [comment]
@wapmorgan, на самом деле список городов, которые неправильно склоняются достаточно большой. Если у вас появится время, обратите, пожалуйста, на них внимание.

Предложный падеж, фраза «Мы открываемся в ...»
**Бор:** -Боре > +Бору
**Иваново/Одинцово:**  -Иванове > +Иваново
**Орёл:** -Ореле > +Орле
**Россошь:** -Россошь > +Россоши
**Чебоксары/Шахты:** -Чебоксары > +Чебоксарах
**Элекстросталь:** -Элекстростале > +Элекстростали

**Comment by wapmorgan** [comment]
Спасибо, возьму это на заметку.
Только проблема с Одинцово/Иваново - это не проблема, а сложившаяся ситуация (большинство не склоняется) - https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B3%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5#%D0%A1%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,_%D0%BE%D0%BA%D0%B0%D0%BD%D1%87%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F_%D0%BD%D0%B0_-%D0%BE%D0%B2(%D0%BE),_-%D1%91%D0%B2(%D0%BE),_-%D0%B5%D0%B2(%D0%BE),_-%D0%B8%D0%BD(%D0%BE),_-%D1%8B%D0%BD(%D0%BE).

**Comment by Nappsel** [comment]
@wapmorgan спасибо за оперативное обновление.
Вы отклонили правку по Одинцово/Иваново, возможно вариант с явным исключением в **$suffixes** будет лучше?
```
if ($name === 'иваново' || 'одинцово')
                    return [
                        self::IMENIT => $prefix.'о',
                        self::RODIT => $prefix.'о',
                        self::DAT => $prefix.'о',
                        self::VINIT => $prefix.'о',
                        self::TVORIT => $prefix.'о',
                        self::PREDLOJ => $prefix.'о',
                    ];
```
Или оставить только строку с предложным падежом.

**Comment by wapmorgan** [comment]
Пока что не решил что делать с названиями на "ово/ево". В википедии утверждается, что такие топонимы изначально склонялись, только в последнее время стало популярно (вопреки правилам) оставлять первоначальную форму.
