### ISSUE TITLE
morphos\S::setEncoding('utf-8') лишнее

### ISSUE THREAD

**Issue by duzun** [wapmorgan/Morphos#40]
В моем проэкте encoding проставляется в зависимости от настроек и сесии.
Фаил `src/initialization.php` мешает в некоторых модулях или просто повторяет то что и так делает фреймворк.

Но что оссобенно привлекло мое внимание это то что `vendor/wapmorgan/morphos/src/S.php` вызывается ооочень часто, даже чаше `vendor/autoload.php`, даже там где библиотека не используется.

Может стоит просто упомянуть в документации что `Morphos` работает только на 'utf-8' и посоветовать вызов `morphos\S::setEncoding('utf-8');`, а `src/initialization.php` удолить из `autoload`?

**Comment by wapmorgan** [comment]
`initialization.php` должен подключаться только один раз - про подключении `vendor/autoload.php`, а вот частые вызовы методов класса `S` - это нормально, так как почти все методы в API его используют. autoload вообще не должен запускаться несколько раз за запрос - это значит у вас где-то не так настроено.

**Comment by wapmorgan** [comment]
Насчёт полного избавления от явной установки кодировки и подгрузки лишнего файла: возможно перенесу в сам класс S инициализацию, но это уже попозже.

**Comment by duzun** [comment]
Проблема не в том что методы ‘S’ вызываются часто - они вообще не вызываются в большинстве запросов - но в каждом запросе загружается файл «S.php», даже в тех частях сайта где Morphus не вызывается.

А что если в проекте 10 библиотек которые задают encoding при autoload?

Думаю что не правильно чтоб библиотека что-либо делало пока к ней не обратиться.

Проект очень полезен :)

**Comment by wapmorgan** [comment]
Убрал установку юникода. Теперь чтобы поставить другу кодировку (например, cp1251), перед использованием функций библиотеки вызовите:
```php
\morphos\S::setEncoding('cp1251');
```
**Note:** Однако даже если убрать подгрузку и вызов S, то подгружается ещё два файла с функциями для языков для всех запросов.

**Comment by duzun** [comment]
Спасибо!

Сделаю апдейт и проверю что к чему.

**Comment by wapmorgan** [comment]
В 3.2.13

**Comment by duzun** [comment]
Протестил 3.2.13, все выглядет хорошо, спасибо за апдейт!

Теперь при каждом запросе к моему приложению composer подгружает **18** фаилов библиотек из `vendor/`, из которых **2** штуки с функциями `Morphos` (было 4). Учитывая что работает `opcache`, это допустимо :-)
