### ISSUE TITLE
Неверное склонение городов с окончанием на "Р" и "О"

### ISSUE THREAD

**Issue by tentonhammer** [wapmorgan/Morphos#41]
Неверное склонение городов с окончанием на "Р" в предложном падеже: например, "КраснодарУ", а должно быть "КраснодарЕ". По сути, все названия, кроме оканчивающихся на "бор/яр" пишутся неправильно. Примеры городов с окончание на "Р" можно посмотреть [здесь](http://bezbukv.ru/scanwords/8/?mask=%24%D1%80). Спасибо!

**Comment by tentonhammer** [comment]
Также имеется проблема с именами городов и сёл с окончанием на "О": должно быть СелихинО, а не СелихинЕ (предл. падеж).

**Comment by wapmorgan** [comment]
1. "Селихине" - традиционно склоняется (https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B3%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5#%D0%A1%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,_%D0%BE%D0%BA%D0%B0%D0%BD%D1%87%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F_%D0%BD%D0%B0_-%D0%BE%D0%B2(%D0%BE),_-%D1%91%D0%B2(%D0%BE),_-%D0%B5%D0%B2(%D0%BE),_-%D0%B8%D0%BD(%D0%BE),_-%D1%8B%D0%BD(%D0%BE)). Уже обсуждалось [здесь](https://github.com/wapmorgan/Morphos/issues/34#issuecomment-416569106)
2. Краснодар склоняется правильно в последней версии (http://morphos.io/try/geography?input=Краснодар).
