### ISSUE TITLE
Краснодар 

### ISSUE THREAD

**Issue by rim89** [wapmorgan/Morphos#50]
Библиотека установлена из composer перед написанием поста.
Не корректно склоняет Краснодар
`use morphos\Russian\GeographicalNamesInflection;
var_dump(
	GeographicalNamesInflection::getCases('Краснодар')
);`
array(6) { ["nominative"]=> string(18) "Краснодар" ["genitive"]=> string(20) "Краснодара" ["dative"]=> string(20) "Краснодару" ["accusative"]=> string(18) "Краснодар" ["ablative"]=> string(22) "Краснодаром" ["prepositional"]=> string(20) "Краснодару" }

При этом в демке на вашем сайте склоняет корректно, Предложный - Краснодаре

**Comment by wapmorgan** [comment]
Оформил релиз **3.2.16** с фиксом по данной проблеме. Обновитесь.
