### ISSUE TITLE
Неправильно склоняет слово "детский"

### ISSUE THREAD

**Issue by EginKaman** [wapmorgan/Morphos#52]
Вот пример: http://morphos.io/try/numerals?number=2&word=%D0%94%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9
Вместо "ы" должно быть "и".

**Comment by wapmorgan** [comment]
А вот теперь есть morphos\Russian\AdjectiveDeclension: `var_dump(morphos\Russian\AdjectiveDeclension::getCases('детский'));`
