### ISSUE TITLE
Не склоняет фамилию Острицкая

### ISSUE THREAD

**Issue by jun-dev** [wapmorgan/Morphos#58]
Например, Елена Острицкая, при склонении будет: Елене Острицкой, или Елены Острицкой.

**Comment by wapmorgan** [comment]
Склонение работает правильно: http://morphos.io/try/names?input=%D0%9E%D1%81%D1%82%D1%80%D0%B8%D1%86%D0%BA%D0%B0%D1%8F+%D0%95%D0%BB%D0%B5%D0%BD%D0%B0
