### ISSUE TITLE
Ordinal numbers bugs

### ISSUE THREAD

**Issue by Mogikan** [wapmorgan/Morphos#60]
Ошибка в файле
https://github.com/wapmorgan/Morphos/blob/6cf69ff8b52190d4a831dbc7587b677351ed8bc5/src/Russian/OrdinalNumeralGenerator.php
50 => 'пятьдесяти', expected 'пятидесяти'
60 => 'шестьдесяти', expected 'шестидесяти'
70 => 'семьдесяти', expected 'семидесяти'
80 => 'восемьдесяти', expected 'восьмидесяти'
Еще сорокоого неправильно. Возможно для 40 не нужен особый случай с префиксом длины 1. Хотелось бы комментариев, зачем особый случай?
$prefix = S::slice($word, 0, $number == 40 ? -1 : -2);

**Comment by wapmorgan** [comment]
`50 => 'пятьдесяти', expected 'пятидесяти'`
Здесь всё кажется верным

**Comment by Mogikan** [comment]
https://numeralonline.ru/
У числительных от пятидесяти до восьмидесяти, от пятисот до девятисот, двести, триста, четыреста склоняются обе части. Перечислим их в таблице ниже.
Падеж	50-80
И.	пятьдесят
Р.	пятидесяти
Д.	пятидесяти
В.	пятьдесят
Т.	пятьюдесятью
П.	о пятидесяти
