### ISSUE TITLE
Склонение сумм с валютами

### ISSUE THREAD

**Issue by dthpto** [wapmorgan/Morphos#64]
Сейчас склоняется только в именительном падеже, а иногда нужно что-то вроде "... в размере ста двадцати пяти тысяч восьмисот одного рубля пятидесяти одной копейки ..."

**Comment by wapmorgan** [comment]
```php
MoneySpeller::spell(123.45, MoneySpeller::RUBLE, MoneySpeller::NORMAL_FORMAT, 'родительный')
```

**Comment by wapmorgan** [comment]
В версии **3.2.20**
