### ISSUE TITLE
Склонение прилагательных

### ISSUE THREAD

**Issue by K0r5hun** [wapmorgan/Morphos#68]
Подскажите, есть ли возможность склонять прилагательные, а именно
"Коммерческий директор" выдаёт "коммерческего", "коммерческему",  "коммерческего"

**Comment by K0r5hun** [comment]
Разобрался. Надо использовать класс AdjectiveDeclension::getCases('коммерческий'), который уже работает, но судя по всему в процессе разработки.
Благодарю за отличную библиотеку!

**Comment by wapmorgan** [comment]
Нет, не в разработке, просто не описан.

**Comment by kerstvo** [comment]
А как определить, является ли слово прилагательным?

**Comment by wapmorgan** [comment]
По окончаниям: ой, ий, ый, ей, ай, ...

**Comment by kerstvo** [comment]
"Гений" не вписывается в это правило. Пробовал определять род прилагательного, если получилось, значит существительное. Но не очень надёжно работает:)

**Comment by wapmorgan** [comment]
В принципе таких слов не много.
В коде библиотеки всего два - https://github.com/wapmorgan/Morphos/blob/5550474d1cc6c8936bca66e86fee43f19c73a41a/src/Russian/RussianLanguage.php#L349
