### ISSUE TITLE
Неправильно склоняет имя "Зинаида" в родительный падеж

### ISSUE THREAD

**Issue by SergeyRock** [wapmorgan/Morphos#69]
Здравствуйте!
Спасибо за библиотеку.

Нашли некорректное поведение:
`
echo \morphos\Russian\inflectName('Зинаида Гринева', \morphos\Russian\Cases::GENITIVE);
`

Пример на сайте:
https://www.uchmet.ru/events/reviews/2449563/

Должно быть: 
Отзыв Зинаид**Ы** Гриневой

Склоняет, как:
Отзыв Зинаид**А** Гриневой

**Comment by SergeyRock** [comment]
Просто Зинаида не склоняет:
http://morphos.io/try/names?input=%D0%97%D0%B8%D0%BD%D0%B0%D0%B8%D0%B4%D0%B0

**Comment by wapmorgan** [comment]
Fixed in d609cd6c0ad379fd918d79a7d37e807f1a5bf926. Check out `dev-master`.
