### ISSUE TITLE
Толстой Алексей Николаевич и фамилии на -йо

### ISSUE THREAD

**Issue by 111ypuk** [wapmorgan/Morphos#7]
Толстой Алексей Николаевич в родительном падеже
 Толстойа Алексея Николаевича
http://morphos.tech/try/names?input=%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%B9+%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9+%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87

**Comment by wapmorgan** [comment]
Спасибо, исправлено!
Также исправлены еще несклоняемые мужские фамилии на `ых`, `ко`, `ово` и `аго` и женские на `ая`.
