### ISSUE TITLE
Неверно работает pluralize со словом "модуль"

### ISSUE THREAD

**Issue by efiand** [wapmorgan/Morphos#72]
Здравствуйте! Спасибо за библиотеку, очень классная!
Но иногда дает сбой:
http://morphos.io/try/numerals?number=7&word=%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C

**Comment by efiand** [comment]
Также обнаружилось неверное склонение слова "Крым" в предложном падеже: http://morphos.io/try/geography?input=%D0%9A%D1%80%D1%8B%D0%BC

**Comment by wapmorgan** [comment]
Крым склоняет правильно, это форма Предложного падежа. Если вы имеете в виду окончание "в Крым*у*", то это уже другая форма. Они иногда отличаются у имён собственных, как здесь. Как интегрировать эту форму пока не придумал

**Comment by wapmorgan** [comment]
Обновлено в 2bb17e0

**Comment by efiand** [comment]
Спасибо!
Да, может неверно выразился, но та самая форма нормативна, в общем, пока прогоняю результат morphos'а снаружи через массив overrides

**Comment by wapmorgan** [comment]
Эта форма называется второй [предложный падеж](http://rusgram.ru/%D0%9F%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B0%D0%B4%D0%B5%D0%B6#12).
Как именно её добавить пока нет соображений, поэтому её и нет.

**Comment by wapmorgan** [comment]
Добавлен падеж [Локативный](https://github.com/wapmorgan/Morphos/blob/master/README-ru.md#%D0%93%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) в географических названиях.
