### ISSUE TITLE
Неправильно склоняется город "Сочи"

### ISSUE THREAD

**Issue by polysalov** [wapmorgan/Morphos#73]
Название города Сочи не склоняется.

**Comment by wapmorgan** [comment]
Не склоняется уже давно. Обновите версию..

**Comment by polysalov** [comment]
В таком случае вам нужно обновить версию в api вашего сайта
![sochi](https://user-images.githubusercontent.com/12642797/76706510-01203800-66f9-11ea-879b-a91d7ac3e179.PNG)
