### ISSUE TITLE
"во Франции" вместо "в Франции"

### ISSUE THREAD

**Issue by DenysNosov** [wapmorgan/Morphos#76]
Как можно географические названия склонять с приставкой В, так чтобы и сама приставка В менялась?

Например:
Во Франции
В Италии

**Comment by wapmorgan** [comment]
https://github.com/wapmorgan/Morphos/blob/master/README-ru.md#%D0%9F%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B3%D0%B8-%D0%B8-%D0%BE%D0%BA%D0%BE%D0%BD%D1%87%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by evolvens** [comment]
Круто 👍 Не заметил
