### ISSUE TITLE
Ошибки в склонении существительных

### ISSUE THREAD

**Issue by abordage** [wapmorgan/Morphos#77]
Автослесарь
Водитель
Воспитатель
Продавец
Секретарь
Токарь
Пекарь
Врач (творительный)

**Comment by wapmorgan** [comment]
Эти слова по признакам определятся как третье склонение, но по сути являются вторым склонением. Остаётся только пополнять список слов, выпадающих из рамок.

**Comment by wapmorgan** [comment]
Добавлено в dfc4d84e6168af6545044d5e9350a1c0ae049e17.
Доступно в dev-master версии.
