### ISSUE TITLE
Ошибка склонения

### ISSUE THREAD

**Issue by vsavritsky** [wapmorgan/Morphos#78]
Апартаментов
Квартир 
и т.п

![image](https://user-images.githubusercontent.com/5252233/79981115-cbffc600-84ac-11ea-9e90-f22479b7a524.png)

![image](https://user-images.githubusercontent.com/5252233/79981168-e0dc5980-84ac-11ea-8385-917d777f0d02.png)

**Comment by wapmorgan** [comment]
Необходимо использовать форму Апартаменты или Квартира, т.е. в ед. числе, им. падеже
