### ISSUE TITLE
Склонение других географических названий

### ISSUE THREAD

**Issue by vsavritsky** [wapmorgan/Morphos#79]
Хотелось бы добавить склонение других географических названий

Например: Рублёво-Успенское шоссе. Сейчас не верно склоняет + удаляет букву ё

![image](https://user-images.githubusercontent.com/5252233/79981442-5b0cde00-84ad-11ea-9323-a0442b398a2c.png)

**Comment by wapmorgan** [comment]
Добавил исключение "Рублёво" в b7dc4138bd9bb29a4a8a11bcdb71b81f06ab11dc. А буква Ё удаляется на сайте, в самом библиотеке нет такого ограничения.
