### ISSUE TITLE
Инфостранные ФИО

### ISSUE THREAD

**Issue by 111ypuk** [wapmorgan/Morphos#8]
Неверно склоняются
Андерсен Ганс Христиан
Милн Алан Александр

**Comment by wapmorgan** [comment]
Ок, я понял что изменить. В ближайшее время сделаю поддержку таких отчеств (?).

**Comment by wapmorgan** [comment]
Исправлено склонение иностранных отчеств:
- http://morphos.tech/try/names?input=%D0%90%D0%BD%D0%B4%D0%B5%D1%80%D1%81%D0%B5%D0%BD+%D0%93%D0%B0%D0%BD%D1%81+%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD
- http://morphos.tech/try/names?input=%D0%9C%D0%B8%D0%BB%D0%BD+%D0%90%D0%BB%D0%B0%D0%BD+%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80
Пока что в dev-master, через несколько дней релизну.
