### ISSUE TITLE
Неправильное склонение некоторых географических названий

### ISSUE THREAD

**Issue by rusproject** [wapmorgan/Morphos#86]
Воронеж -> Воронежом (должно быть Воронежем)
![image](https://user-images.githubusercontent.com/62891105/85236644-66867200-b428-11ea-9bdd-72e5e4d8f2bd.png)

**Comment by rusproject** [comment]
Могу ошибаться, но, также [Анино](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B8%D0%BD%D0%BE) (как и [Аннино](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%BD%D0%B8%D0%BD%D0%BE)) неправильно склоняются, что-то подсказывает, что они не должны склоняться вообще.

**Comment by rusproject** [comment]
Алма-Ата - первое слово не склоняется.

**Comment by sngrl** [comment]
Присоединяюсь, есть проблемы с географическими названиями. Вот так обрабатываются некоторые регионы России (везде предложный падеж):

> в Адыгеи
> в Кабардине-Балкарии
> в Карачаеве-Черкесии
> в Марем Эле
> в Чечни

**Comment by bzaar** [comment]
@leonardooleg, вот так:

1. [http://ws3.morpher.ru/russian/adjectivize?s=Италия](http://ws3.morpher.ru/russian/adjectivize?s=Италия&format=json) и потом вот так:
2. [http://ws3.morpher.ru/russian/genders?s=итальянский](http://ws3.morpher.ru/russian/genders?s=итальянский&format=json)

[Документация](http://morpher.ru/ws3/#adjectivize)

**Comment by wapmorgan** [comment]
https://github.com/wapmorgan/Morphos/compare/c51d206...659fdff
Исправления на Воронеж, Адыгея, Алма-Ату и другие.

**Comment by wapmorgan** [comment]
Не удалось найти правила, по которым Анино и остальные не должны склоняться

**Comment by wapmorgan** [comment]
@leonardooleg у Morphos нет такой функциональности, можно воспользоваться словарями или другими библиотеками

**Comment by wapmorgan** [comment]
Обновление в dev-master, можно пробовать

**Comment by rusproject** [comment]
> Не удалось найти правила, по которым Анино и остальные не должны склоняться

Судя по Грамоте.ру, раньше такие названия склонялись, а сейчас - почти все - нет. Да и уху (лично моему) привычнее как-то если говоришь "В Аннино" а не "В Аннине". 

> Географические названия славянского происхождения, оканчивающиеся на   -ово, -ево, -ино, -ыно, традиционно склонялись: в Останкине, в Переделкине, к Болдину, до Пулкова, из Косова. Тенденция к употреблению несклоняемого варианта сложилась лишь в последние десятилетия. Иными словами, новая норма – не в Люблине, а в Люблино

http://gramota.ru/class/istiny/istiny_1_toponimy/#:~:text=1.-,%D0%92%20%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%BA%D0%B2%D0%B0%D1%88%D0%B8%D0%BD%D0%BE%20%D0%B8%D0%BB%D0%B8%20%D0%B2%20%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%BA%D0%B2%D0%B0%D1%88%D0%B8%D0%BD%D0%B5%3F,%D1%81%D0%BA%D0%BB%D0%BE%D0%BD%D1%8F%D1%8E%D1%82%D1%81%D1%8F%20%D0%B8%20%D0%BD%D0%B8%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0%20%D0%BD%D0%B5%20%D1%81%D0%BA%D0%BB%D0%BE%D0%BD%D1%8F%D0%BB%D0%B8%D1%81%D1%8C.

**Comment by wapmorgan** [comment]
Анино, Люблино и так далее, судя по правилам в [википедии](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B3%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5#%D0%A1%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,_%D0%BE%D0%BA%D0%B0%D0%BD%D1%87%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F_%D0%BD%D0%B0_-%D0%BE%D0%B2(%D0%BE),_-%D1%91%D0%B2(%D0%BE),_-%D0%B5%D0%B2(%D0%BE),_-%D0%B8%D0%BD(%D0%BE),_-%D1%8B%D0%BD(%D0%BE)) - по словам 
* _кандидата к.ф.н., главред. ГРАМОТА.РУ П. Владимира*
* _к.ф.н. Р. А. Агеевой_
* по информации в справочнике _Русская речь в эфире_

они либо могут как склоняться, так и не склоняться, либо обязательно склоняются без топонима.

**Comment by stepanenko3** [comment]
Так же есть проблемы со склонением городов Украины. Например: Белая Церковь

**Comment by Edd-G** [comment]
Присоединюсь.

Неверное склонение, город Домодедово.
Не склоняет его никто, кроме тех самых КФН, объясняющих правила русского языка.

Грамматика постоянно меняется.

Странно слышать подобные аргументы КФН: "вспомним у Пушкина: «История села Горюхина», у Лермонтова: «Недаром помнит вся Россия про день Бородина!»"
Можно более ранние времена, поэтов и писателей вспомнить)

**Comment by h4mpy** [comment]
еще несколько неправильных склонений
Камень-на-оби
Нарьян-Мар
Урус-Мартан

города Спас-, Усть-, Соль-
http://gramma.ru/SPR/?id=3.4
