### ISSUE TITLE
Двойные Фамилии

### ISSUE THREAD

**Issue by 111ypuk** [wapmorgan/Morphos#9]
склоняется только последняя часть фамилии. А на http://morphos.tech дефис удаляется
Соколов-Микитов Иван Сергеевича
Кучера-Бози Людмила 
Копусов-Долинин Алексей Иванович
Мартен-Люган Аньес

**Comment by wapmorgan** [comment]
Исправлено в **3.2.1**. Можете обновиться и проверить. Спасибо за информацию!

**Comment by wapmorgan** [comment]
Вроде все хорошо теперь склоняется. Только подскажите, как правильно склонять "Кучера-Бози"?
В родительном падеже будет Кучере-Бози или Кучеры-Бози?

**Comment by 111ypuk** [comment]
Если исходить из 
https://www.analizfamilii.ru/Kuchera/skloneniye.html
то Кучеры

**Comment by wapmorgan** [comment]
- [Соколов-Микитов Иван Сергеевича](http://morphos.tech/try/names?input=%D0%A1%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE%D0%B2-%D0%9C%D0%B8%D0%BA%D0%B8%D1%82%D0%BE%D0%B2+%D0%98%D0%B2%D0%B0%D0%BD+%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B5%D0%B2%D0%B8%D1%87%D0%B0)
- [Кучера-Бози Людмила](http://morphos.tech/try/names?input=%D0%9A%D1%83%D1%87%D0%B5%D1%80%D0%B0-%D0%91%D0%BE%D0%B7%D0%B8+%D0%9B%D1%8E%D0%B4%D0%BC%D0%B8%D0%BB%D0%B0)
- [Копусов-Долинин Алексей Иванович](http://morphos.tech/try/names?input=%D0%9A%D0%BE%D0%BF%D1%83%D1%81%D0%BE%D0%B2-%D0%94%D0%BE%D0%BB%D0%B8%D0%BD%D0%B8%D0%BD+%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9+%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87)
- [Мартен-Люган Аньес](http://morphos.tech/try/names?input=%D0%9C%D0%B0%D1%80%D1%82%D0%B5%D0%BD-%D0%9B%D1%8E%D0%B3%D0%B0%D0%BD+%D0%90%D0%BD%D1%8C%D0%B5%D1%81)
Исправлено.
