### ISSUE TITLE
Russian\TimeSpeller::spellDifference, TimeSpeller::DIRECTION for time in future

### ISSUE THREAD

**Issue by askurihin** [wapmorgan/Morphos#92]
## Описание

При использовании `Russian\TimeSpeller::spellDifference` с аргументом `TimeSpeller::DIRECTION` время в будущем (с предлогом `через`) для 1-й минуты и секунды выводится неверно.

## Как воспроизвести:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
echo morphos\Russian\TimeSpeller::spellDifference(time() + 61, morphos\TimeSpeller::DIRECTION);  
```
Выводит `через 1 минута` (тоже самое для секунд)

## Ожидаемый вывод:

`через 1 минуту`

**Comment by wapmorgan** [comment]
Обновлено в dev-master.
